### ISSUE TITLE
backbone model

### ISSUE THREAD

**Issue by achintski** [mecarill/2pcnet#3]
Dear sir,
Thank you for sharing your work！
I have a question about how to modify the backbone model.The backbone used in your code is Faster RCNN, and I want to modify it to Yolov7. 
Since I am just getting started with object detection, I am not familiar with modifying the code. I kindly ask you to provide some ideas for modification (backbone part and train part), and I will modify it by myself according to your ideas.
Looking forward to hearing from you！
Thanks in advance！

**Comment by mecarill** [comment]
Hello achintski! Due to the architecture of this current method, it would not be simple to copy/paste it into YOLO. This is because we make use of the RPN which is the first part of the 2-stage object detector (FRCNN) whereas YOLO is 1-stage. 

You could potentially use the outputs of the teacher in YOLO as a proxy for the RPN outputs but we cannot guarantee performance as we have not tested it.
